<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import PageHeader from '@/components/PageHeader.vue'
import UiIcon from '@/components/UiIcon.vue'
import EmptyState from '@/components/EmptyState.vue'
import StatusBadge from '@/components/StatusBadge.vue'
import AdminFeedback from './AdminFeedback.vue'
import PrescriptionItems from './PrescriptionItems.vue'
import {useAdminPage,items,entry} from './useAdminPage'
import {formatDate} from '@/lib/format'
const route=useRoute(), kind=computed(()=>String(route.meta.kind || 'reports'))
const {data,loading,error,load}=useAdminPage(()=>`/admin/appointments/${route.params.id}/${kind.value}`)
</script>
<template><div class="admin-view"><PageHeader :title="kind==='reports'?'挂号检查报告':'挂号处方明细'" description="按本次就诊关联信息查看报告与处方。"><RouterLink class="button button-secondary" :to="data.appointment?.patientId?`/app/admin/patients/${data.appointment.patientId}`:'/app/admin/patients'"><UiIcon name="chevron-left" :size="17" />返回患者档案</RouterLink></PageHeader><AdminFeedback :loading="loading" :error="error" @retry="load" /><template v-if="!loading"><section class="panel"><div class="admin-panel-heading"><div><h2>就诊 #{{ data.appointment?.id }}</h2><p>{{ data.patientUser?.realName || '患者' }} · {{ data.doctorUser?.realName || '医生' }} · {{ data.doctor?.department || '科室待登记' }}</p></div><StatusBadge :status="data.appointment?.status" /></div><dl class="admin-info-grid"><div><dt>预约日期</dt><dd>{{ formatDate(data.appointment?.appointmentDate) }}</dd></div><div><dt>预约时间</dt><dd>{{ data.appointment?.appointmentTime }}</dd></div><div><dt>患者主诉</dt><dd>{{ data.appointment?.symptoms || '未填写' }}</dd></div></dl></section><section v-if="kind==='reports'" class="panel"><div class="admin-panel-heading"><div><h2>本次就诊报告 <span class="admin-count">{{ items(data,'reports').length }}</span></h2><p>查看检查结果与出具状态</p></div></div><EmptyState v-if="!items(data,'reports').length" title="本次就诊暂无报告" /><div v-else class="table-scroll"><table class="admin-table"><thead><tr><th>项目名称</th><th>报告日期</th><th>状态</th><th>费用支付</th><th>操作</th></tr></thead><tbody><tr v-for="r in items(data,'reports')" :key="r.id"><td>{{ entry(data,'examinationMap',r.id).name || r.reportType || '诊疗报告' }}</td><td>{{ formatDate(r.reportDate,true) }}</td><td><StatusBadge :status="r.status" /></td><td>{{ r.paid?'已支付':'未支付' }}</td><td><RouterLink class="admin-link" :to="{path:`/app/admin/reports/${r.id}/preview`,query:{returnPatientId:String(data.appointment.patientId)}}">查看报告</RouterLink></td></tr></tbody></table></div></section><template v-else><section v-if="!items(data,'prescriptions').length" class="panel"><EmptyState title="本次就诊暂无处方" /></section><section v-for="p in items(data,'prescriptions')" :key="p.id" class="panel"><div class="admin-panel-heading"><div><h2>{{ p.prescriptionNumber || `处方 #${p.id}` }}</h2><p>开具时间 {{ formatDate(p.createdAt,true) }} · {{ p.paid?'已支付':'未支付' }}</p></div><StatusBadge :status="p.status" /></div><PrescriptionItems :items="data.itemsMap?.[p.id] || []" :total="data.totalAmountMap?.[p.id]" /><div class="admin-form-footer"><RouterLink class="button button-secondary" :to="{path:`/app/admin/pharmacy/${p.id}`,query:{returnPatientId:String(data.appointment.patientId)}}">{{ p.status==='PENDING'?'进入药房处理':'查看发药详情' }}<UiIcon name="arrow-right" :size="16" /></RouterLink></div></section></template></template></div></template>
